authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
    path('verify/<email>/<key>/', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.urls import path
import basketapp.views as basket

app_name = 'basketapp'

urlpatterns = [
    path('', basket.basket, name='list'),
    path('add/<int:pk>/', basket.basket_add, name='add'),
    path('remove/<int:pk>/', basket.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket.basket_edit, name='edit'),
]

geekshop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from mainapp import urls
from . import settings
from .views import main, contact

app_name = 'geekshop'

urlpatterns = [
    path('', main, name='index'),
    path('admin/', admin.site.urls),
    path('contact/', contact, name='contacts'),
    path('products/', include(urls)),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import path
from .views import products, product

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='index'),
    path('<int:pk>', product, name='product'),
    path('category/<int:index>/', products, name='category'),
    path('category/<int:index>/page/<int:page>/', products, name='page'),
]

mainapp/models.py
from django.db import models


# Create your models here.

class ProductCategory(models.Model):
    name = models.CharField(
        max_length=64,
        unique=True,
        verbose_name='имя',
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True,
        null=True,
    )
    is_active = models.BooleanField(
        verbose_name='активна',
        default=True,
    )
    created = models.DateTimeField(
        auto_now_add=True
    )
    updated = models.DateTimeField(
        auto_now=True
    )

    def __str__(self):
        return self.name


class Product(models.Model):
    objects = None
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Категория',
    )
    name = models.CharField(
        verbose_name='имя продукта',
        max_length=128,
    )
    image = models.ImageField(
        upload_to='products_img',
        blank=True,
    )
    short_desc = models.CharField(
        max_length=256,
        verbose_name='краткое описание',
        blank=True,
    )
    description = models.TextField(
        verbose_name='описание продукта',
        max_length=500,
        blank=True,
    )
    price = models.DecimalField(
        verbose_name='цена продукта',
        max_digits=8,
        decimal_places=2,
        default=0,
    )
    quantity = models.PositiveIntegerField(
        verbose_name='количество на складе',
        default=0
    )
    is_active = models.BooleanField(
        default=True,
    )

    def __str__(self):
        return f'{self.name} ({self.category.name})'

mainapp/views.py
import random
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from basketapp.models import Basket
from .models import ProductCategory
from .models import Product
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    return []


def get_hot_product():
    return random.sample(list(Product.objects.all()), 1)


def get_related(select_product):
    return Product.objects.filter(category=select_product.category).exclude(id=select_product.id)[:3]


@login_required
def products(request, index=None, page=1):
    if index is not None and index != 0:
        category = get_object_or_404(ProductCategory, id=index)
        products_list = Product.objects.filter(category_id=index, is_active=True).order_by('price')
    else:
        products_list = Product.objects.all().order_by('price')
        category = {'name': 'все', 'id': 0}

    paginator = Paginator(products_list, 4)

    try:
        paginator_page = paginator.page(page)
    except PageNotAnInteger:
        paginator_page = paginator.page(1)
    except EmptyPage:
        paginator_page = paginator.page(paginator.num_pages)

    categories = ProductCategory.objects.all()
    context = {
        'title': 'Каталог',
        'categories': categories,
        'category': category,
        'products': paginator_page,
    }
    return render(request, 'products_list.html', context=context)


@login_required
def product(request, pk):
    product = Product.objects.get(id=pk)
    context = {
        'product': product,
        'categories': ProductCategory.objects.all(),
        'related': get_related(product),
        'hot': get_hot_product()
    }
    if request.is_ajax():
        return JsonResponse({'price': product.price})
    return render(request, 'products.html', context=context)

mainapp/templates/categories.html
<div class="links clearfix">
    <ul class="links-menu">
        <li><a href="{% url 'mainapp:index' %}" {% if category.id == 0 %} class="active" {% endif %}>ВСЕ</a></li>
        {% for item in categories %}
        {% if item.is_active %}
        <li><a href="{% url 'mainapp:index' %}category/{{ item.id }}/" {% if category.id == item.id %} class="active" {% endif %}> {{ item.name|upper }}</a></li>
        {% endif %}
        {% endfor %}
    </ul>
</div>

mainapp/templates/products.html
{% extends 'main_layout.html' %}
{% load static %}

{% block content %}
<div class="hero-white">
    {% include 'main_menu.html' %}
</div>
<div class="details">
    {% include 'categories.html' %}
    <div class="details-products mb-2">
        <div class="details-slider">
            <div class="slider-product">
                <img src="/media/{{ product.image }}">
            </div>
            <div class="slider-control">
                <div class="block">
                    <a href="#"><img src="{% static 'geekshop/img/controll.jpg' %}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="{% static 'geekshop/img/controll1.jpg' %}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="{% static 'geekshop/img/controll2.jpg' %}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
            </div>
        </div>
        <div class="description">
            <h3 class="big-bold">{{ product.name }}</h3>
<!--            <h3 class="red">горячее предложение</h3>-->
            <h3 class="red"></h3>
            <p class="price"> {{ product.price|floatformat:"-2" }} <span>руб</span></p>
            <a href="{% url 'basket:add' product.id %}" class="red-button">
                заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
            <div class="description-text">
                {% lorem 1 p %}
                {{ product.description }}
            </div>
        </div>
    </div>

    {% if related %}
        {% include 'related.html' %}
    {% endif %}
</div>
{% endblock %}

mainapp/templates/products_list.html
{% extends 'main_layout.html' %}
{% load static %}

{% block content %}
<div class="hero-white">
        {% include 'main_menu.html' %}
</div>
<div class="details">
    {% include 'categories.html' %}
    <h2>Категория: {{ category.name|title }}</h2>
    <div class="paginator">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                {% if products.has_previous %}
                    <li class="page-item"><a class="page-link" href="{% url 'mainapp:page' category.id products.previous_page_number %}">Previous</a></li>
                {% endif %}

                {% for page in products.paginator.page_range %}
                    <li class="page-item {% if page == products.number %} active {% endif %}"><a class="page-link" href="{% url 'mainapp:page' category.id page %}">{{ page }}</a></li>
                {% endfor %}
                {% if products.has_next %}
                    <li class="page-item"><a class="page-link" href="{% url 'mainapp:page' category.id products.next_page_number %}">Next</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
    <div class="tab-content">
        {% for product in products%}
        <div class="block">
            <a href="{% url 'mainapp:product' product.id %}"><img src="/media/{{ product.image }}" alt="">
                <div class="text">
                    <img src="{% static 'geekshop/img/icon-hover.png' %}" alt="img">
                    <h4>{{ product.name }}</h4>
                    <p>{{ product.short_desc }}</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>

</div>
{% endblock %}

mainapp/templates/related.html
{% load static %}

<div class="related">
    <div class="title clearfix">
        <h2>Похожие продукты</h2>
        <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
    </div>
    <div class="related-products clearfix">
        {% for item in related %}
        <div class="block">
            <a href="{% url 'mainapp:product' item.id %}"><img src="/media/{{ item.image }}" alt="">
                <div class="text">
                    <img src="{% static 'img/icon-hover.png' %}" alt="img">
                    <h4>{{ item.name }}</h4>
                    <p>{{ item.short_desc }}</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>