adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path

app_name = 'adminapp'

urlpatterns = [
    path('user/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('user/read/', adminapp.UsersListView.as_view(), name='users'),
    path('user/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('user/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    path('categories/list/', adminapp.CategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('products/list/category/<int:pk>/', adminapp.ProductsListView.as_view(), name='products'),
    path('products/create/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),
]

authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
    path('verify/<email>/<key>/', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.urls import path
import basketapp.views as basket

app_name = 'basketapp'

urlpatterns = [
    path('', basket.basket, name='list'),
    path('add/<int:pk>/', basket.basket_add, name='add'),
    path('remove/<int:pk>/', basket.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket.basket_edit, name='edit'),
]

geekshop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from mainapp import urls
from . import settings
from .views import main, contact

app_name = 'geekshop'

urlpatterns = [
    path('', main, name='index'),
    path('admin/', admin.site.urls),
    path('contact/', contact, name='contacts'),
    path('products/', include(urls)),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import path
from .views import products, product

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='index'),
    path('<int:pk>', product, name='product'),
    path('category/<int:index>/', products, name='category'),
    path('category/<int:index>/page/<int:page>/', products, name='page'),
]

geekshop/views.py
from django.shortcuts import render
from mainapp.models import Product


def main(request):
    products = Product.objects.all()[:4]
    context = {
        'title': 'Магазин',
        'products': products,
    }
    return render(request, 'index.html', context=context)


def contact(request):
    context = {
        'title': 'Контакты',
    }
    return render(request, 'contact.html', context=context)

geekshop/templates/contact.html
{% extends 'main_layout.html' %}

{% block content %}
<div class="hero">
    {% include 'main_menu.html' %}
    <h1>наши контакты</h1>
</div>

<div class="location">
    <div class="location-1">
        <i class="fa fa-map-marker fa-5x"></i>
        <h4>Москва</h4>
        <div class="contacts">
            <h5>Телефон</h5>
            <p>+7-888-888-8888</p>
        </div>
        <div class="contacts">
            <h5>Email</h5>
            <p>info@geekshop.ru</p>
        </div>
        <div class="contacts">
            <h5>Адрес</h5>
            <p>В пределах МКАД</p>
        </div>
    </div>
    <div class="location-1">
        <i class="fa fa-map-marker fa-5x"></i>
        <h4>Москва</h4>
        <div class="contacts">
            <h5>Телефон</h5>
            <p>+7-888-888-8888</p>
        </div>
        <div class="contacts">
            <h5>Email</h5>
            <p>info@geekshop.ru</p>
        </div>
        <div class="contacts">
            <h5>Адрес</h5>
            <p>В пределах МКАД</p>
        </div>
    </div>
    <div class="location-1">
        <i class="fa fa-map-marker fa-5x"></i>
        <h4>Москва</h4>
        <div class="contacts">
            <h5>Телефон</h5>
            <p>+7-888-888-8888</p>
        </div>
        <div class="contacts">
            <h5>Email</h5>
            <p>info@geekshop.ru</p>
        </div>
        <div class="contacts">
            <h5>Адрес</h5>
            <p>В пределах МКАД</p>
        </div>
    </div>
</div>
<div class="clr"></div>
{% endblock %}

geekshop/templates/footer.html
<div class="footer">
    <div class="clearfix">
        <div class="text-footer">
            <h3>контакты</h3>
        </div>
        <div class="text-footer">
            <h3>полезная информация</h3>
        </div>
        <div class="text-footer clearfix">
            <h3>Оставайтесь на связи</h3>
            <p>Подписаться на новости и рассылки</p>
            <form>
                <input type="email" name="email" placeholder="ваш email">
                <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
            </form>
        </div>
    </div>
    <p class="small">&copy; GB {% now 'Y' %}</p>
    <div class="social">
        <a href="#" class="social1"></a>
        <a href="#" class="social2"></a>
        <a href="#" class="social3"></a>
        <a href="#" class="social4"></a>
    </div>
    <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
</div>

geekshop/templates/index.html
{% extends 'main_layout.html' %}
{% load static %}

{% block content %}
<div class="slider">
        {% include 'main_menu.html' %}
    <div class="text-slider">
        <h3 class="green">тенденции</h3>
        <h3 class="big"> удобные стулья</h3>
        <p>Новый уровень комфорта. Отличные характеристики.</p>
        <a href="#" class="button-order">заказать <img src="{% static 'geekshop/img/arrow.png' %}" alt=""></a>
    </div>
    <div class="navi">
        <a href="#"></a><a href="#"></a><a href="#"></a>
    </div>
</div>
<div class="featured">
    <div class="featured-menu">
        <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
    </div>
    <a class="explore" href="#">показать все <img src="{% static 'geekshop/img/arrow.png' %}" alt=""></a>
    <div class="clearfix">
    </div>
    <div class="tab-content">
        {% for product in products%}
        <div class="block">
            <a href="{% url 'mainapp:product' product.id %}"><img src="/media/{{ product.image }}" alt="">
                <div class="text">
                    <img src="{% static 'geekshop/img/icon-hover.png' %}" alt="img">
                    <h4>{{ product.name }}</h4>
                    <p>{{ product.short_desc }}</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
<div class="clr"></div>
{% endblock %}

geekshop/templates/main_layout.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'geekshop/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'geekshop/fonts/font-awesome/css/font-awesome.css' %}">
    {% block js_head %}
    {% endblock %}
    {% block css %}
    {% endblock %}
</head>
<body>
<div class="cont p-0">
    {% block content %}
    {% endblock %}
    <div class="clr"></div>
</div>

{% block footer %}
{% include 'footer.html' %}
{% endblock %}

{% block js %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock %}
</body>
</html>

geekshop/templates/main_menu.html
<div class="header clearfix">
    <a href="/" class="logo"></a>
    <ul class="menu nav nav-pills">
        {% url 'index' as index_url %}
        <li class="nav-item">
            <a href="{{ index_url }}"
               class="nav-link{% if request.path == index_url %} active_menu{% endif %}">домой</a>
        </li>
        {% url 'mainapp:index' as product_url %}
        <li class="nav-item">
            <a href="{{ product_url }}" class="nav-link{% if product_url in request.path %} active_menu{% endif %}">продукты</a>
        </li>
        {% url 'contacts' as contacts_url %}
        <li class="nav-item">
            <a href="{{ contacts_url }}" class="nav-link{% if request.path == contacts_url %} active_menu{% endif %}">контакты</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">
                {{ user.first_name|default:'Пользователь' }}</a>
            <ul class="dropdown-menu">
                <li>
                    <a href="{% url 'authapp:edit' %}" class="dropdown-item">Профиль</a>
                </li>
                {% if user.is_superuser%}
                <li>
                    <a href="{% url 'admin_staff:users' %}" class="dropdown-item">Админка</a>
                </li>
                {% endif %}
                <li>
                    <a href="{% url 'order:list' %}" class="dropdown-item">Заказы</a>
                </li>
                <li>
                    <a href="{% url 'authapp:logout' %}" class="dropdown-item">Выйти</a>
                </li>
            </ul>
        </li>
        {% else %}
        <li class="nav-item">
            <a href="{% url 'authapp:login' %}" class="nav-link">Войти</a>
        </li>
        {% endif %}
    </ul>
    {% if user.is_authenticated %}
    <a href="{% url 'basket:list' %}" class="basket fa fa-shopping-basket">{{ basket_items.0.total_quantity }} шт.
        {{ basket_items.0.total_cost|floatformat:"-2" }} руб. </a>
    {% endif %}
    <a href="#" class="search"></a>
</div>