adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path

app_name = 'adminapp'

urlpatterns = [
    path('user/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('user/read/', adminapp.UsersListView.as_view(), name='users'),
    path('user/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('user/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    path('categories/list/', adminapp.CategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('products/list/category/<int:pk>/', adminapp.ProductsListView.as_view(), name='products'),
    path('products/create/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),
]

authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
    path('verify/<email>/<key>/', authapp.verify, name='verify'),
]

geekshop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from mainapp import urls
from . import settings
from .views import main, contact

app_name = 'geekshop'

urlpatterns = [
    path('', main, name='index'),
    path('admin/', admin.site.urls),
    path('contact/', contact, name='contacts'),
    path('products/', include(urls)),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms
from authapp.models import ShopUser
from authapp.forms import ShopUserEditForm
from mainapp.models import ProductCategory, Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control form-control-sm'
            field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control form-control-sm'
            field.help_text = ''

adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator

from adminapp.forms import ShopUserAdminEditForm, ProductCategoryEditForm, ProductEditForm
from authapp.forms import ShopUserRegisterForm
from authapp.models import ShopUser
from mainapp.models import Product, ProductCategory

from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView


# Пользователи

class UsersListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'
    context_object_name = 'objects'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'админка/пользователи'
        return context


class UserCreateView(CreateView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    form_class = ShopUserRegisterForm
    success_url = reverse_lazy('adminapp:users')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'пользователи/создание'
        return context


class UserUpdateView(UpdateView):
    model = ShopUser
    object = ''
    template_name = 'adminapp/user_update.html'
    # fields = ['username', 'first_name', 'last_name', 'age', 'avatar', 'is_active']
    form_class = ShopUserAdminEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'пользователи/редактирование'
        return context

    def get_success_url(self):
        self.object = self.get_object()
        return reverse_lazy('adminapp:user_update', args=[self.object.id])


class UserDeleteView(DeleteView):
    model = ShopUser
    object = ''
    template_name = 'adminapp/user_delete.html'
    context_object_name = 'user_to_delete'
    success_url = reverse_lazy('adminapp:users')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'пользователи/удаление'
        return context

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


# Категории

class CategoryListView(ListView):
    model = ProductCategory
    template_name = 'adminapp/categories.html'
    context_object_name = 'objects'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'админка/категории'
        return context


class CategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    form_class = ProductCategoryEditForm
    success_url = reverse_lazy('adminapp:categories')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'категории/создание'
        return context


class CategoryUpdateView(UpdateView):
    model = ProductCategory
    object = ''
    template_name = 'adminapp/category_update.html'
    form_class = ProductCategoryEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории/редактирование'
        return context

    def get_success_url(self):
        self.object = self.get_object()
        return reverse_lazy('adminapp:category_update', args=[self.object.id])


class CategoryDeleteView(DeleteView):
    model = ProductCategory
    object = ''
    template_name = 'adminapp/category_delete.html'
    context_object_name = 'cat_to_delete'
    success_url = reverse_lazy('adminapp:categories')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'категории/удаление'
        return context

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


# Товары/Продукты

class ProductsListView(ListView):
    model = Product
    template_name = 'adminapp/products.html'
    context_object_name = 'objects'
    category = None

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        self.category = self.kwargs.get('pk')
        return super().dispatch(*args, **kwargs)

    def get_queryset(self):
        return self.model.objects.filter(category__id=self.category).order_by('name')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'админка/продукт'
        context["category"] = self.category
        return context


class ProductUpdateView(UpdateView):
    model = Product
    object = ''
    template_name = 'adminapp/product_update.html'
    form_class = ProductEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'продукт/редактирование'
        self.object = self.get_object()
        context["category"] = self.object.category
        return context

    def get_success_url(self):
        self.object = self.get_object()
        return reverse_lazy('adminapp:product_update', args=[self.object.id])


class ProductCreateView(CreateView):
    model = Product
    template_name = 'adminapp/product_update.html'
    form_class = ProductEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'продукт/создание'
        context["category"] = {'id': self.kwargs.get('pk')}
        return context

    def get_success_url(self):
        return reverse_lazy('adminapp:products', args=[self.kwargs.get('pk')])


class ProductDeleteView(DeleteView):
    model = Product
    object = ''
    template_name = 'adminapp/product_delete.html'
    context_object_name = 'product_to_delete'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'продукт/удаление'
        return context

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy('adminapp:products', args=[self.object.category.id])

adminapp/templates/adminapp/base.html
<!doctype html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'geekshop/fonts/font-awesome/css/font-awesome.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'adminapp/admin_style.css' %}">
    <title>{{ title|title }}</title>
    {% block css_head %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
            crossorigin="anonymous"></script>
    <script src="{% static 'adminapp/script.js' %}"></script>
    {% block js_head %}
    {% endblock %}
</head>
<body id="body-pd">
<header class="header" id="header">
    <div class="header_toggle"><i class='bx bx-menu' id="header-toggle"></i></div>
    <div class="header_img"><img src="/media/{{ user.avatar|default:'avatar-default.png' }}" alt=""></div>
</header>
<div class="l-navbar" id="nav-bar">
    <nav class="nav">
        <div>
            <a href="{% url 'index' %}" class="nav_logo">
                <i class='bx bx-layer nav_logo-icon'></i><span class="nav_logo-name">Магазин</span>
            </a>
            <div class="nav_list">
                {% include 'adminapp/includes/inc_menu.html' %}
            </div>
        </div>
        <a href="{% url 'authapp:logout' %}" class="nav_link">
            <i class='bx bx-log-out nav_icon'></i>
            <span class="nav_name">Выход</span>
        </a>
    </nav>
</div>
<div class="height-100 bg-light">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% block content%}

<div class="container-fluid">
    <h1 class="mt-4">Категории</h1>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fa fa-table mr-1"></i>
            Категории
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-sm table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Категория</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for object in objects%}
                    <tr {% if not object.is_active %}  style="opacity: 0.5;" {% endif %}>
                        <td class="text-left align-middle">{{ object.name }}</td>
                        <td>
                            <div class="btn-group" role="group" aria-label="actions">
                                <button type="button" class="btn btn-primary">
                                    <a class="text-white text-decoration-none" href="{% url 'admin_staff:products' object.id %}">подробнее</a>
                                </button>
                                <button type="button" class="btn btn-warning">
                                    <a class="text-dark text-decoration-none" href="{% url 'admin_staff:category_update' object.id %}">редактировать</a>
                                </button>
                                {% if object.is_active %}
                                <button type="button" class="btn btn-danger">
                                    <a class="text-white text-decoration-none" href="{% url 'admin_staff:category_delete' object.id %}">удалить</a>
                                </button>
                                {% endif %}
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer">
            <a href="{% url 'admin_staff:category_create' %}">
                <button class="btn btn-success">Новая категория</button>
            </a>
        </div>
    </div>
</div>


{% endblock %}

adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% block content %}
<div class="alert alert-danger col-4 m-auto" role="alert">
    Уверены, что хотите удалить категорию - {{ cat_to_delete.name }} ?
    <form action="{% url 'adminapp:category_delete' cat_to_delete.pk %}" method="post">
        {% csrf_token %}
        <div class="m-2 d-flex justify-content-center">
            <button class="btn btn-primary mr-3">
                <a class="text-white text-decoration-none" href="{% url 'adminapp:categories' %}">Отмена</a>
            </button>
            <button type="submit" class="btn btn-danger">
                Удалить
            </button>
        </div>
    </form>
</div>
{% endblock %}

adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="col-6 m-auto shadow">
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control btn-success" type="submit" value="сохранить">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'adminapp:categories' %}">
            к списку категорий
        </a>
    </button>
</div>
{% endblock %}

adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% block content %}
<div class="alert alert-danger col-4 m-auto" role="alert">
    Уверены, что хотите удалить - {{ product_to_delete.name }} ?
    <form action="{% url 'adminapp:product_delete' product_to_delete.pk %}" method="post">
        {% csrf_token %}
        <div class="m-2 d-flex justify-content-center">
            <button class="btn btn-primary mr-3">
                <a class="text-white text-decoration-none" href="{% url 'adminapp:products' product_to_delete.category.id %}">Отмена</a>
            </button>
            <button type="submit" class="btn btn-danger">
                Удалить
            </button>
        </div>
    </form>
</div>
{% endblock %}

adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="col-6 m-auto shadow">
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control btn-success" type="submit" value="сохранить">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'adminapp:products' category.id %}">
            к списку продуктов
        </a>
    </button>
</div>
{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}

<div class="container-fluid">
    <h1 class="mt-4">Продукты
        {% if category %}
        :<span>{{ category.name }}</span>
        {% endif %}
    </h1>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fa fa-table mr-1"></i>
            <a href="{% url 'admin_staff:categories' %}">Категории</a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-sm table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr class="text-center">
                        <th>Изображение</th>
                        <th>Имя</th>
                        <th>Описание</th>
                        <th>Количество</th>
                        <th>Цена</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for object in objects %}
                    <tr {% if not object.is_active %}  style="opacity: 0.5;" {% endif %}>
                        <td class="text-center"><img src="/media/{{object.image|default:'products_images/default.jpg'}}"
                                 alt="{{ object.name }}" style="width:50px;">
                        </td>
                        <td class="text-center align-middle">{{ object.name|title }}</td>
                        <td class="text-center align-middle">{{ object.short_desc|title }}</td>
                        <td class="text-center align-middle">{{ object.quantity }}</td>
                        <td class="text-center align-middle">{{ object.price }} руб</td>
                        <td>
                            <div class="btn-group" role="group" aria-label="actions">
                                <button class="btn btn-warning">
                                    <a class="text-dark" href="{% url 'admin_staff:product_update' object.id %}">редактировать</a>
                                </button>
                                {% if object.is_active %}
                                <button class="btn btn-danger">
                                    <a class="text-white" href="{% url 'admin_staff:product_delete' object.id %}">удалить</a>
                                </button>
                                {% endif %}
                            </div>
                        </td>
                    </tr>
                    {% endfor%}
                    </tbody>
                </table>
                <div class="card-footer">
                    <button class="btn btn-success">
                        <a class="text-white" href="{% url 'admin_staff:product_create' category %}">
                            новый продукт
                        </a>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
<div class="alert alert-danger col-4 m-auto" role="alert">
    Уверены, что хотите удалить пользователя - {{ user_to_delete.username }}
    {% if user_to_delete.first_name %}
        ({{ user_to_delete.first_name|title }}
        {% if user_to_delete.last_name %}
            {{ user_to_delete.last_name|title }}
        {% endif %})
    {% endif %}
    ?
    <form action="{% url 'adminapp:user_delete' user_to_delete.pk %}" method="post">
        {% csrf_token %}
        <div class="m-2 d-flex justify-content-center">
            <button class="btn btn-primary mr-3">
                <a class="text-white text-decoration-none" href="{% url 'adminapp:users' %}">Отмена</a>
            </button>
            <button type="submit" class="btn btn-danger">
                Удалить
            </button>
        </div>
    </form>
</div>
{% endblock %}

adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="col-6 m-auto shadow">
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control btn-success" type="submit" value="сохранить">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'adminapp:users' %}">
            к списку пользователей
        </a>
    </button>
</div>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content%}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Пользователи</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fa fa-table mr-1"></i>
                Пользователи
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-sm table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr class="text-center">
                            <th>Аватар</th>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эд. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                            <th>Вход</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for user in objects%}
                        <tr class="text-center align-middle" {% if not user.is_active %}  style="opacity: 0.5;" {% endif %}>
                            <td style="width: 10%">
                                <img src="/media/{{ user.avatar|default:'avatar-default.png' }}" class="img-thumbnail rounded-circle w-25" alt="Avatar">
                            </td>
                            <td class="align-middle"><a href="{% url 'admin_staff:user_update' user.id %}" style="color: dodgerblue">{{ user.username }}</a></td>
                            <td class="align-middle">{{ user.first_name }}</td>
                            <td class="align-middle">{{ user.last_name }}</td>
                            <td class="align-middle">{{ user.email }}</td>
                            <td class="text-center align-middle">
                                {% if user.is_staff %}
                                <i class="fa fa-check-circle text-success"></i>
                                {% else %}
                                <i class="fa fa-times-circle text-primary"></i>
                                {% endif %}
                            </td>
                            <td class="text-center align-middle">
                                {% if user.is_active %}
                                <i class="fa fa-check-circle text-success"></i>
                                {% else %}
                                <i class="fa fa-times-circle text-primary"></i>
                                {% endif %}
                            </td>
                            <td class="align-middle">{{ user.last_login }}</td>
                            <td class="align-middle">
                                {% if user.is_active %}
                                <a href="{% url 'admin_staff:user_delete' user.id %}" class="text-danger"><i class="fa fa-times-circle"></i></a>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'admin_staff:user_create' %}">
                    <button class="btn btn-success">Создать</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}